# Cadastrar usuário:

POST http://localhost:3003/user
Content-Type: application/json

{
    "name": "Adria Tavares",
    "email": "adria12367@gmail.com",
    "password": "123457",
    "phoneNumber": "85997743646",
    "zipCode": "10012-434",
    "roleId": 2
}

###
#Login:

POST http://localhost:3003/auth
Content-Type: application/json

{
    "email": "adria12367@gmail.com",
    "password": "123457" 
}