# Cadastrar usuário:

POST http://localhost:3003/user
Content-Type: application/json

{
    "name": "Adria Tavares",
    "email": "adria12367@gmail.com",
    "password": "123457",
    "phoneNumber": "1234567891011",
    "zipCode": "10012-434678",
    "roleId": 2
}

###
#Login:

POST http://localhost:3003/auth
Content-Type: application/json

{
    "email": "adria12367@gmail.com",
    "password": "123457" 
}