# Cadastrar usuário:

POST http://localhost:3003/user
Content-Type: application/json

{
    "name": "Sofia Pitta",
    "email": "sofia@gmail.com",
    "password": "123456",
    "phoneNumber": "(11)99912-3456",
    "zipCode": "10012-434",
    "roleId": 2
}

###
#Login:

POST http://localhost:3003/auth
Content-Type: application/json

{
    "email": "sofia@gmail.com",
    "password": "123456" 
}

###
#Pegar dados do usuário:

GET http://localhost:3003/userd3073ae5-3d42-4d7e-bbce-79dffee15bb5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQzMDczYWU1LTNkNDItNGQ3ZS1iYmNlLTc5ZGZmZWUxNWJiNSIsInJvbGUiOjIsImlhdCI6MTcxMzUyMjUxNSwiZXhwIjoxNzE0MTI3MzE1fQ.jnUOrFd700mmvrN5qMDen4UbIiXaC1WbXorPoJ3nohM